version: "3.8"
services:
  nginx:
    image: hieptt149/multi-docker-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

  server:
    image: hieptt149/multi-docker-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  client:
    image: hieptt149/multi-docker-client
    mem_limit: 128m
    hostname: client

  worker:
    image: hieptt149/multi-docker-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
